num = int(input('Digite um número para ver sua tabuada: '))
print('-' * 12)
print('{} X {} = {}'.format(num, 1, num*1))
print('{} X {} = {}'.format(num, 1, num*2))
print('{} X {} = {}'.format(num, 1, num*3))
print('{} X {} = {}'.format(num, 1, num*4))
print('{} X {} = {}'.format(num, 1, num*5))
print('{} X {} = {}'.format(num, 1, num*6))
print('{} X {} = {}'.format(num, 1, num*7))
print('{} X {} = {}'.format(num, 1, num*8))
print('{} X {} = {}'.format(num, 1, num*9))
print('{} X {} = {}'.format(num, 1, num*10))
print('-' * 12)
