nome = str(input("Digite seu nome completo: ")).strip()
nomeMais = nome.upper()
print(nomeMais)
nomeMinus = nome.lower()
print(nomeMinus)
print("Seu nome tem ao todo {} letras.".format(len(nome) - nome.count(' ')))
print("Seu primeiro nome tem {} letras.".format(nome.find(' ')))